openapi: "3.0.0"
info:
  title: "Anthropic AI API"
  version: "1.0.0"
  description: "API for interacting with Anthropic's conversational AI models."
servers:
  - url: "https://api.anthropic.com/v1"

paths:
  /messages:
    post:
      summary: "Create a Message"
      description: "Send messages to the assistant to generate responses."
      parameters:
        - name: "anthropic-version"
          in: "header"
          required: true
          schema:
            type: "string"
            example: "2023-06-01"
        - name: "x-api-key"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                model:
                  type: "string"
                  example: "claude-2"
                messages:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      role:
                        type: "string"
                        enum: ["user", "assistant"]
                      content:
                        type: "string"
                temperature:
                  type: "number"
                  description: "Sampling temperature to control randomness of response."
                  example: 0.7
                max_tokens:
                  type: "integer"
                  description: "Maximum tokens to generate."
                  example: 256
      responses:
        "200":
          description: "Successful response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  completion:
                    type: "string"
                  usage:
                    type: "object"
                    properties:
                      tokens:
                        type: "integer"

  /messages/streaming:
    post:
      summary: "Streaming Messages"
      description: "Stream responses incrementally using server-sent events."
      parameters:
        - name: "anthropic-version"
          in: "header"
          required: true
          schema:
            type: "string"
            example: "2023-06-01"
        - name: "x-api-key"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                model:
                  type: "string"
                  example: "claude-2"
                messages:
                  type: "array"
                  items:
                    type: "object"
                    properties:
                      role:
                        type: "string"
                        enum: ["user", "assistant"]
                      content:
                        type: "string"
                stream:
                  type: "boolean"
                  description: "Whether to stream responses incrementally."
                  example: true
      responses:
        "200":
          description: "Streaming response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  event:
                    type: "string"
                  data:
                    type: "object"

  /complete:
    post:
      summary: "Create a Text Completion"
      description: "Generate text completions for prompts."
      parameters:
        - name: "anthropic-version"
          in: "header"
          required: true
          schema:
            type: "string"
            example: "2023-06-01"
        - name: "x-api-key"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                model:
                  type: "string"
                  example: "claude-2"
                prompt:
                  type: "string"
                max_tokens_to_sample:
                  type: "integer"
                  description: "Maximum tokens to sample."
                  example: 256
                stream:
                  type: "boolean"
                  description: "Whether to stream responses incrementally."
                  example: false
      responses:
        "200":
          description: "Successful text completion"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  completion:
                    type: "string"
                  stop_reason:
                    type: "string"

  /streaming:
    post:
      summary: "Streaming Text Completion"
      description: "Stream text completions incrementally using server-sent events."
      parameters:
        - name: "anthropic-version"
          in: "header"
          required: true
          schema:
            type: "string"
            example: "2023-06-01"
        - name: "x-api-key"
          in: "header"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                model:
                  type: "string"
                  example: "claude-2"
                prompt:
                  type: "string"
                stream:
                  type: "boolean"
                  example: true
      responses:
        "200":
          description: "Streaming text completion response"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  event:
                    type: "string"
                  data:
                    type: "object"
